export type VehicleStatus = "available" | "reserved" | "sold" | "in-transit";
export type VehicleCondition = "Foreign Used" | "Locally Used" | "Brand New";

export interface Vehicle {
  slug: string;
  make: string;
  model: string;
  trim: string;
  year: number;
  priceKES: number;
  mileageKm: number;
  fuel: "Petrol" | "Diesel" | "Hybrid" | "Electric" | "Plug-in Hybrid";
  transmission: "Automatic" | "Manual" | "CVT";
  drive: "AWD" | "4WD" | "FWD" | "RWD";
  engineCc: number;
  engineSummary: string;
  powerHp?: number;
  torqueNm?: number;
  accelSec?: number;
  bodyType: "SUV" | "Sedan" | "Hatchback" | "Coupe" | "Pickup" | "Wagon";
  seats: number;
  exterior: string;
  interior: string;
  condition: VehicleCondition;
  status: VehicleStatus;
  location: string;
  origin: "Kenya" | "Japan" | "United Kingdom";
  featured: boolean;
  images: string[];
  description: string;
  features: string[];
}

export const vehicles: Vehicle[] = [
  {
    slug: "toyota-land-cruiser-v8-zx-kdt",
    make: "Toyota",
    model: "Land Cruiser V8",
    trim: "ZX Bruno Edition",
    year: 2016,
    priceKES: 7300000,
    mileageKm: 0,
    fuel: "Petrol",
    transmission: "Automatic",
    drive: "4WD",
    engineCc: 4600,
    engineSummary: "4.6L V8 Petrol",
    bodyType: "SUV",
    seats: 7,
    exterior: "Pearl White",
    interior: "Bruno Edition leather",
    condition: "Locally Used",
    status: "available",
    location: "Nairobi Showroom",
    origin: "Kenya",
    featured: true,
    images: [
      "/images/vehicles/toyota-land-cruiser-v8-zx-kdt/1.webp",
      "/images/vehicles/toyota-land-cruiser-v8-zx-kdt/2.webp",
      "/images/vehicles/toyota-land-cruiser-v8-zx-kdt/3.webp",
      "/images/vehicles/toyota-land-cruiser-v8-zx-kdt/4.webp",
      "/images/vehicles/toyota-land-cruiser-v8-zx-kdt/5.webp",
      "/images/vehicles/toyota-land-cruiser-v8-zx-kdt/6.webp",
      "/images/vehicles/toyota-land-cruiser-v8-zx-kdt/7.webp",
      "/images/vehicles/toyota-land-cruiser-v8-zx-kdt/8.webp",
      "/images/vehicles/toyota-land-cruiser-v8-zx-kdt/9.webp",
      "/images/vehicles/toyota-land-cruiser-v8-zx-kdt/10.webp",
    ],
    description:
      "A supremely capable Land Cruiser V8 ZX in the coveted Bruno Edition, blending executive luxury with the legendary 4.6-litre V8's effortless power. Low genuine mileage, tip-top condition inside and out, accident-free with ready documents. Purchase comes with a complimentary full tank of fuel and a complimentary service. Josam's way of ensuring your ownership story starts perfectly.",
    features: [
      "4.6L V8 Petrol: Powerful, Smooth & Refined",
      "Bruno Edition leather interior",
      "7 leather seats, spacious executive cabin",
      "Front powered seats with memory function",
      "Tesla-style radio infotainment",
      "Working sunroof + cooler box",
      "Height control suspension",
      "Keyless entry & multi-functional steering wheel",
      "Daytime running lights",
      "Brand new tyres",
      "Accident-free | Ready documents",
      "🎁 FREE full tank + complimentary service on purchase",
    ],
  },
  {
    slug: "porsche-cayenne-platinum-edition-kdh",
    make: "Porsche",
    model: "Cayenne",
    trim: "Platinum Edition",
    year: 2015,
    priceKES: 4950000,
    mileageKm: 0,
    fuel: "Petrol",
    transmission: "Automatic",
    drive: "AWD",
    engineCc: 3600,
    engineSummary: "3.6L V6 Petrol",
    bodyType: "SUV",
    seats: 5,
    exterior: "White",
    interior: "Premium leather",
    condition: "Locally Used",
    status: "available",
    location: "Nairobi Showroom",
    origin: "Kenya",
    featured: true,
    images: [
      "/images/vehicles/porsche-cayenne-platinum-edition-kdh/1.webp",
      "/images/vehicles/porsche-cayenne-platinum-edition-kdh/2.webp",
      "/images/vehicles/porsche-cayenne-platinum-edition-kdh/3.webp",
      "/images/vehicles/porsche-cayenne-platinum-edition-kdh/4.webp",
      "/images/vehicles/porsche-cayenne-platinum-edition-kdh/5.webp",
      "/images/vehicles/porsche-cayenne-platinum-edition-kdh/6.webp",
      "/images/vehicles/porsche-cayenne-platinum-edition-kdh/7.webp",
      "/images/vehicles/porsche-cayenne-platinum-edition-kdh/9.webp",
      "/images/vehicles/porsche-cayenne-platinum-edition-kdh/10.webp",
      "/images/vehicles/porsche-cayenne-platinum-edition-kdh/11.webp",
    ],
    description:
      "A well-preserved 2015 Porsche Cayenne Platinum Edition with low genuine mileage. Locally owned, carefully maintained and presented in tip-top condition. The smooth 3.6-litre V6 petrol drives through Porsche's renowned automatic gearbox with effortless pace, while the Platinum Edition's signature alloys and premium leather cabin set it apart from the standard car. Ready documents; just buy and drive.",
    features: [
      "3.6L V6 Petrol engine, Automatic transmission",
      "Multi-terrain drive selection",
      "Premium leather upholstery",
      "Working sunroof",
      "Electric tailgate, hands-free access",
      "Multi-functional steering wheel",
      "Reverse camera with proximity sensors",
      "Daytime running lights",
      "Low genuine mileage | Well maintained",
      "Tip-top condition, clean interior & exterior",
      "Ready documents | Just buy & drive",
    ],
  },
  {
    slug: "audi-q5-45-tfsi-quattro-2022",
    make: "Audi",
    model: "Q5",
    trim: "45 TFSI quattro S line",
    year: 2022,
    priceKES: 6850000,
    mileageKm: 38500,
    fuel: "Petrol",
    transmission: "Automatic",
    drive: "AWD",
    engineCc: 2000,
    engineSummary: "2.0L TFSI Turbocharged I4",
    powerHp: 261,
    torqueNm: 370,
    accelSec: 6.1,
    bodyType: "SUV",
    seats: 5,
    exterior: "Glacier White",
    interior: "Black leather",
    condition: "Foreign Used",
    status: "available",
    location: "Nairobi Showroom",
    origin: "United Kingdom",
    featured: true,
    images: [],
    description:
      "A beautifully kept example of Audi's benchmark mid-size luxury SUV. The 45 TFSI pairs a 2.0-litre turbocharged engine with the legendary quattro all-wheel-drive system and a seamless 7-speed S tronic gearbox, delivering 261 PS with effortless composure. Finished in Glacier White over black leather with the S line package, it arrives freshly imported, fully inspected and ready for its next custodian.",
    features: [
      "S line exterior & interior package",
      "quattro all-wheel drive",
      "7-speed S tronic dual-clutch",
      "Virtual Cockpit digital cluster",
      "MMI Navigation plus with touch",
      "Panoramic glass sunroof",
      "Heated front sport seats",
      "3-zone automatic climate control",
      "Power tailgate with gesture control",
      "LED matrix headlights",
      "Rear-view camera & park sensors",
      "Cruise control with speed limiter",
    ],
  },
  {
    slug: "range-rover-sport-hse-dynamic-2023",
    make: "Land Rover",
    model: "Range Rover Sport",
    trim: "HSE Dynamic D350",
    year: 2023,
    priceKES: 22500000,
    mileageKm: 17400,
    fuel: "Diesel",
    transmission: "Automatic",
    drive: "AWD",
    engineCc: 3000,
    engineSummary: "3.0L Ingenium I6 MHEV",
    powerHp: 350,
    torqueNm: 700,
    accelSec: 6.0,
    bodyType: "SUV",
    seats: 5,
    exterior: "Santorini Black",
    interior: "Ebony Windsor leather",
    condition: "Foreign Used",
    status: "available",
    location: "Nairobi Showroom",
    origin: "United Kingdom",
    featured: true,
    images: [],
    description:
      "The definitive statement in modern luxury SUVs. This Range Rover Sport HSE Dynamic pairs the silky D350 mild-hybrid straight-six with Terrain Response 2 and electronic air suspension, cosseting five occupants in Windsor leather while retaining genuine all-terrain authority. Supplied with a verified service history and full pre-delivery inspection.",
    features: [
      "Electronic air suspension",
      "Terrain Response 2",
      "13.1-inch Pivi Pro touchscreen",
      "Meridian Signature sound system",
      "Windsor leather heated & cooled seats",
      "Panoramic sliding roof",
      "Soft-close doors",
      "Pixel LED headlights",
      "360° camera with wade sensing",
      "Adaptive cruise with steering assist",
    ],
  },
  {
    slug: "mercedes-benz-gle-450-amg-line-2022",
    make: "Mercedes-Benz",
    model: "GLE",
    trim: "450 4MATIC AMG Line",
    year: 2022,
    priceKES: 14900000,
    mileageKm: 24800,
    fuel: "Petrol",
    transmission: "Automatic",
    drive: "AWD",
    engineCc: 3000,
    engineSummary: "3.0L Turbo I6 + EQ Boost",
    powerHp: 367,
    torqueNm: 500,
    accelSec: 5.7,
    bodyType: "SUV",
    seats: 5,
    exterior: "Obsidian Black",
    interior: "Macchiato beige leather",
    condition: "Foreign Used",
    status: "available",
    location: "Nairobi Showroom",
    origin: "Japan",
    featured: false,
    images: [],
    description:
      "Effortless pace meets S-Class-inspired refinement. The GLE 450's inline-six with EQ Boost delivers seamless thrust through the 9G-Tronic, while the AMG Line cabin wraps its occupants in double-stitched leather, Burmester sound and the twin 12.3-inch MBUX widescreen. A Japan-sourced grade-4.5 unit with full documentation.",
    features: [
      "AMG Line exterior & interior",
      "AIRMATIC air suspension",
      "MBUX dual 12.3-inch displays",
      "Burmester surround sound",
      "Panoramic sliding sunroof",
      "Heated & ventilated front seats",
      "360° camera with active park assist",
      "Ambient lighting, 64 colours",
      "Active Distance Assist DISTRONIC",
    ],
  },
  {
    slug: "toyota-land-cruiser-300-zx-2022",
    make: "Toyota",
    model: "Land Cruiser 300",
    trim: "ZX",
    year: 2022,
    priceKES: 19800000,
    mileageKm: 29200,
    fuel: "Diesel",
    transmission: "Automatic",
    drive: "4WD",
    engineCc: 3300,
    engineSummary: "3.3L Twin-Turbo Diesel V6",
    powerHp: 305,
    torqueNm: 700,
    accelSec: 7.4,
    bodyType: "SUV",
    seats: 7,
    exterior: "Precious White Pearl",
    interior: "Black semi-aniline leather",
    condition: "Foreign Used",
    status: "available",
    location: "Nairobi Showroom",
    origin: "Japan",
    featured: true,
    images: [],
    description:
      "The king of African roads in its most refined generation. The ZX flagship pairs the 3.3-litre twin-turbo diesel V6 with a 10-speed automatic and full-time 4WD with three locks, seating seven in semi-aniline leather. Full import documentation available on request.",
    features: [
      "3.3L twin-turbo diesel, 700 Nm",
      "10-speed automatic, full-time 4WD",
      "Multi-Terrain Select & Crawl Control",
      "Toyota Safety Sense suite",
      "12.3-inch infotainment with JBL audio",
      "Heated & ventilated seats, first & second row",
      "Power tailgate with kick sensor",
      "7-seat configuration",
      "Around-view monitor",
    ],
  },
  {
    slug: "porsche-cayenne-s-2021",
    make: "Porsche",
    model: "Cayenne",
    trim: "S",
    year: 2021,
    priceKES: 16500000,
    mileageKm: 31000,
    fuel: "Petrol",
    transmission: "Automatic",
    drive: "AWD",
    engineCc: 2900,
    engineSummary: "2.9L Twin-Turbo V6",
    powerHp: 440,
    torqueNm: 550,
    accelSec: 5.0,
    bodyType: "SUV",
    seats: 5,
    exterior: "Moonlight Blue",
    interior: "Black leather",
    condition: "Foreign Used",
    status: "reserved",
    location: "Nairobi Showroom",
    origin: "United Kingdom",
    featured: false,
    images: [],
    description:
      "The sports car of the SUV world. A 440 PS twin-turbo V6, adaptive air suspension and Porsche Active Suspension Management give the Cayenne S poise no rival matches, wrapped in a discreet yet unmistakable silhouette. Porsche Approved history, fully inspected on arrival.",
    features: [
      "Adaptive air suspension with PASM",
      "Sport Chrono package",
      "BOSE surround sound",
      "Porsche Communication Management",
      "Panoramic roof system",
      "Heated 18-way adaptive sport seats",
      "Lane change & lane keep assist",
      "Power steering plus",
    ],
  },
  {
    slug: "lexus-lx-600-executive-2023",
    make: "Lexus",
    model: "LX 600",
    trim: "Executive",
    year: 2023,
    priceKES: 24500000,
    mileageKm: 12600,
    fuel: "Petrol",
    transmission: "Automatic",
    drive: "4WD",
    engineCc: 3400,
    engineSummary: "3.4L Twin-Turbo V6",
    powerHp: 409,
    torqueNm: 650,
    accelSec: 6.9,
    bodyType: "SUV",
    seats: 4,
    exterior: "Graphite Black",
    interior: "Sunflare semi-aniline leather",
    condition: "Foreign Used",
    status: "available",
    location: "Nairobi Showroom",
    origin: "Japan",
    featured: false,
    images: [],
    description:
      "The four-seat Executive is Lexus at its most indulgent: reclining rear captain's chairs with ottoman, a Mark Levinson reference system and the effortless 409 PS twin-turbo V6. Rarely available locally; this is a flagship in the truest sense.",
    features: [
      "Executive 4-seat layout with ottomans",
      "Mark Levinson 25-speaker audio",
      "Rear-seat entertainment, dual 11.4-inch",
      "Active height control & adaptive suspension",
      "Lexus Safety System+ 2.5",
      "Semi-aniline leather, massage seats",
      "Cool box & refrigerated console",
      "Power running boards",
    ],
  },
  {
    slug: "bmw-x5-xdrive40i-2023",
    make: "BMW",
    model: "X5",
    trim: "xDrive40i M Sport",
    year: 2023,
    priceKES: 15800000,
    mileageKm: 21300,
    fuel: "Petrol",
    transmission: "Automatic",
    drive: "AWD",
    engineCc: 3000,
    engineSummary: "3.0L TwinPower Turbo I6",
    powerHp: 381,
    torqueNm: 520,
    accelSec: 5.5,
    bodyType: "SUV",
    seats: 5,
    exterior: "Mineral White",
    interior: "Cognac Sensafin",
    condition: "Foreign Used",
    status: "available",
    location: "Nairobi Showroom",
    origin: "United Kingdom",
    featured: false,
    images: [],
    description:
      "The benchmark sporting luxury SUV. BMW's creamy B58 inline-six, adaptive M suspension and the sweeping Curved Display make this X5 as compelling on a highway sweep as it is in the school run. M Sport package, Harman Kardon audio and verified UK provenance.",
    features: [
      "M Sport package",
      "BMW Curved Display, iDrive 8",
      "Adaptive M suspension",
      "Harman Kardon surround sound",
      "Panoramic glass roof",
      "Comfort Access & soft-close doors",
      "Parking Assistant Plus",
      "Heated front & rear seats",
      "M Sport brakes",
    ],
  },
  {
    slug: "range-rover-vogue-autobiography-2022",
    make: "Land Rover",
    model: "Range Rover",
    trim: "Autobiography P530 LWB",
    year: 2022,
    priceKES: 32000000,
    mileageKm: 9800,
    fuel: "Petrol",
    transmission: "Automatic",
    drive: "AWD",
    engineCc: 4400,
    engineSummary: "4.4L Twin-Turbo V8",
    powerHp: 530,
    torqueNm: 750,
    accelSec: 4.6,
    bodyType: "SUV",
    seats: 5,
    exterior: "Borasco Grey",
    interior: "Caraway Windsor leather",
    condition: "Foreign Used",
    status: "in-transit",
    location: "En route, Mombasa, ETA 4 weeks",
    origin: "United Kingdom",
    featured: true,
    images: [],
    description:
      "The fifth-generation Range Rover in long-wheelbase Autobiography form. The definitive luxury SUV, full stop. A 530 PS twin-turbo V8, rear-axle steering, executive-class rear seating and near-silent running. Currently in transit; secure it ahead of arrival with a refundable reservation.",
    features: [
      "4.4L twin-turbo V8, 530 PS",
      "Long wheelbase executive seating",
      "Rear-axle steering",
      "Meridian Signature Reference audio",
      "24-way heated/cooled massage seats",
      "Sliding panoramic roof",
      "Electronic air suspension with eHorizon",
      "Soft-close doors & powered tailgate",
      "ClearSight interior rear-view mirror",
    ],
  },
  {
    slug: "toyota-hilux-double-cabin-2021",
    make: "Toyota",
    model: "Hilux",
    trim: "Double Cabin",
    year: 2021,
    priceKES: 5750000,
    mileageKm: 0,
    fuel: "Diesel",
    transmission: "Automatic",
    drive: "4WD",
    engineCc: 2400,
    engineSummary: "2.4L Diesel",
    bodyType: "Pickup",
    seats: 5,
    exterior: "White",
    interior: "Fabric/leather",
    condition: "Foreign Used",
    status: "available",
    location: "Nairobi Showroom",
    origin: "Japan",
    featured: false,
    images: [
      "/images/vehicles/toyota-hilux-double-cabin-2021/1.webp",
      "/images/vehicles/toyota-hilux-double-cabin-2021/2.webp",
      "/images/vehicles/toyota-hilux-double-cabin-2021/3.webp",
      "/images/vehicles/toyota-hilux-double-cabin-2021/4.webp",
      "/images/vehicles/toyota-hilux-double-cabin-2021/5.webp",
      "/images/vehicles/toyota-hilux-double-cabin-2021/6.webp",
      "/images/vehicles/toyota-hilux-double-cabin-2021/7.webp",
      "/images/vehicles/toyota-hilux-double-cabin-2021/8.webp",
      "/images/vehicles/toyota-hilux-double-cabin-2021/9.webp",
      "/images/vehicles/toyota-hilux-double-cabin-2021/10.webp",
    ],
    description:
      "A 2021 Toyota Hilux Double Cabin in tip-top condition with low genuine mileage, well maintained and lightly driven. The proven 2.4-litre diesel engine pairs with a smooth automatic gearbox and switchable 4WD, making this an effortlessly capable everyday workhorse and weekend adventurer alike. Ready documents; just buy and drive.",
    features: [
      "2.4L Diesel engine, efficient & proven",
      "Automatic transmission",
      "4WD optional, on & off road capability",
      "Multi-functional steering wheel",
      "Keyless entry",
      "Lane departure warning",
      "Blind spot monitoring",
      "Low genuine mileage",
      "Tip-top condition, clean interior & exterior",
      "Ready documents | Just buy & drive",
    ],
  },
];

export function getVehicle(slug: string): Vehicle | undefined {
  return vehicles.find((v) => v.slug === slug);
}

export function similarVehicles(vehicle: Vehicle, count = 3, pool: Vehicle[] = vehicles): Vehicle[] {
  return pool
    .filter((v) => v.slug !== vehicle.slug)
    .sort((a, b) => {
      const score = (x: Vehicle) =>
        (x.make === vehicle.make ? 2 : 0) + (x.bodyType === vehicle.bodyType ? 1 : 0);
      return score(b) - score(a);
    })
    .slice(0, count);
}
